"""add celestial_objects

Revision ID: 15537c2ee16e
Revises: d65e34ab84a2
Create Date: 2026-07-01 00:46:10.476490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15537c2ee16e'
down_revision = 'd65e34ab84a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celestial_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ra', sa.Float(), nullable=False),
    sa.Column('dec', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celestial_objects')
    # ### end Alembic commands ###
