"""Add API settings to User model

Revision ID: 8dc30e76d3a0
Revises: 1e11ffb06e70
Create Date: 2026-05-02 01:41:27.474438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc30e76d3a0'
down_revision = '1e11ffb06e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('astrometry_api_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('telescopius_base_url', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telescopius_base_url')
        batch_op.drop_column('astrometry_api_key')

    # ### end Alembic commands ###
