"""Link Observations and GalleryImages

Revision ID: c48e59ac7a18
Revises: 8dc30e76d3a0
Create Date: 2026-05-02 02:18:58.712366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48e59ac7a18'
down_revision = '8dc30e76d3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_gallery_images_observation_id', 'observations', ['observation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gallery_images', schema=None) as batch_op:
        batch_op.drop_constraint('fk_gallery_images_observation_id', type_='foreignkey')
        batch_op.drop_column('observation_id')

    # ### end Alembic commands ###
